### ISSUE TITLE
Potential For Double Voting

### ISSUE THREAD

**Issue by frerghost** [agileware/au.com.agileware.elections#10]
WordPress v6.2.2 CiviCRM v5.63.2

In the instant case, we have a Board of Directors whom total 7. We are green across the dashboard. It operates as expected through the Nomination cycle. As the screenshot demonstrates, though, it gives the option to Nominate again. I did verify that it allows such to be submitted at least to the screen where you would submit again with all the fields and dropdowns. I didn't want to compromise the election so I simply did not execute a second submission. In fact, using WP User Switch, I can resubmit through any valid Board Member. I am the only Admin and it happens with me, as well, ergo I presume it is a bug.

This is the screenshot documenting it: https://imgur.com/a/VFzLvJ8

**Comment by agileware-justin** [comment]
@frerghost you can nominate as many times as you want. There is no limit on nominations, which is distinctly different to voting.

**Comment by frerghost** [comment]
Very good. I appreciate the information and clarification. Please consider the matter closed. Great Extension, by the way!

**Comment by agileware-justin** [comment]
If your organisation realises the cost and effort saved by holding an election online, consider showing your appreciation by sending a few bucks to the Agileware team, use this link https://github.com/sponsors/agileware
