### ISSUE TITLE
Button missing on "Submit Nominations" page in CiviCRM Elections extension

### ISSUE THREAD

**Issue by Hwessinx** [agileware/au.com.agileware.elections#9]
Trying to use the Election extension to CiviCRM. Version 5.50, under WP 6.2.2, and Election version 1.2.3.  Issue: on the "View and Submit Nominations" page, there shall be a Button for nomination of candidates. This button does not exist on our version.

We run a test site for trial work. We have not activated "Outgoing email" on this server.

Do you have a suggestion for the solution of this issue. Needed for us to proceed with the election function later on our production site!

**Comment by agileware-justin** [comment]
@Hwessinx can you provide a screenshot?

**Comment by Hwessinx** [comment]
Hi Justin.

Please find enclosed a screen shot of the "View and submit Nominations"
page.
I cannot proceed beyond this page. Perhaps there are some settings that you
require which I have not included on the CiviCRM set up.

Best Regards

Claes (i.e. Hwessings)


[image: image.png]

**Comment by agileware-justin** [comment]
@Hwessinx 

Upload your image to the Github Issue, https://github.com/agileware/au.com.agileware.elections/issues/9

Replying via email does not seem to work

**Comment by Hwessinx** [comment]
Hi Justin,

Sorry about that.
Let's try here! I'm not fully versed with GitHub, but it might work better here.

<img width="1413" alt="Screenshot 2023-06-21 at 10 23 52" src="https://github.com/agileware/au.com.agileware.elections/assets/84439803/3107dec9-2c11-4b97-9101-b404b1fce4f2">

<img width="1439" alt="Screenshot 2023-06-21 at 10 36 15" src="https://github.com/agileware/au.com.agileware.elections/assets/84439803/60ae7a9b-7591-4263-8942-9df8625f71ae">

I let the warnings remain om page 2, so that you can judge if it has any impact. 
On page two it refers to a button to click in order to add a candidate..  Not there. Even if I scroll down.


Best regards
Claes

**Comment by Hwessinx** [comment]
Hi Justin,

did you receive my screen shots on GitHub??

Claes

**Comment by agileware-justin** [comment]
@Hwessinx I can see that there are no positions defined for the election, so you need to complete these steps, https://github.com/agileware/au.com.agileware.elections/blob/master/docs/admin_add_position.md

There are also a lot of CiviCRM related warnings and errors on the page - you should also fix all those. Particularly the missing CiviCRM base page error.

**Comment by Hwessinx** [comment]
Hi Justin,

Thanks for your response. FYI, I have of course registered Positions, but I had not done it in this particular screenshot. I have tried a number of ways to circumvent the situation, and still the screen-shot says that it should be a registration button in the page...

<img width="1440" alt="image" src="https://github.com/agileware/au.com.agileware.elections/assets/84439803/75220f52-6d80-4901-bd0a-1841b65f330a">


I have also fixed the problem with the WP Base Page.

And as can be seen the "Button" is still missing. I saw from your reference  (nominate_user.md) that the button shall say "Nominate" but it does not appear on my screen!

Hope you can give it another go, Please.

Claes

**Comment by agileware-justin** [comment]
@Hwessinx you need to view the election on the front-end, not the back-end (CiviCRM admin) on the website.

Make sure you have completed these steps, https://github.com/agileware/au.com.agileware.elections/blob/master/docs/setup.md#create-pages-for-the-election-listing-and-individual-election

Then view the election on the website pages.

**Comment by Hwessinx** [comment]
Hi Justin,

Sorry I got it all wrong from the beginning. I will try the front-end approach. Thanks for your patience, (until I run into problems again)!!  😇

Claes
